name: Copy new and updated course content to website repo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    #env:
      #GITHUB_ACCESS_TOKEN: ${{ secrets.SYNC_WEBSITE }}

    steps:
      - name: Checkout course materials
        uses: actions/checkout@v2
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          repository: stat20/website
          path: './website'
          GITHUB_TOKEN: ${{ secrets.SYNC_WEBSITE }}

      # Runs a set of commands using the runners shell
      - name: Copy materials from course-materials to website
        run: |
          # copy lectures located in dirs with leading digit
          for week in $(ls -d lectures/[0-9]*); do
           # make a new directory if needed (if not it will say it already exists, which should be fine)
           if [ ! -d "./website/content/${week}" ]; then
             mkdir ./website/content/${week}
           fi
           # copy landing page
           cp -p ${week}/index.md ./website/content/${week}/
           # copy a directory and all its contents
           #cp -pr /some/path/lecs/${week}/assets /other/path/another/place/
           # copy files ending in .html and .css
           #cp  /some/path/lecs/${week}/*.{html,css} /other/path/another/place/
          done
          
      - name: Commit and push changes to website repo
        run: |
          cd ./website
          git status
          git log
          git remote -v
          git config --global user.email "andrewbray@berkeley.edu"
          git config --global user.name "andrewpbray"
          git add content/lectures/04/index.md
          git commit -am "copied over from course-materials"
          git remote set-url --push origin https://your_username:$GITHUB_TOKEN@github.com/your/repo
          git push
