name: Copy new and updated course content to website repo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Checkout course materials
        uses: actions/checkout@v2
      - name: Checkout website
        uses: actions/checkout@v2
        with:
          repository: stat20/website
          path: './website'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          pwd
          ls
          ls ./website

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          # copy lectures located in dirs with leading digit
          for week in $(ls -d lectures/[0-9]*); do
           # make a new directory if needed (if not it will say it already exists, which should be fine)
           if [ ! -d "./website/content/${week}" ]; then
             mkdir ./website/content/${week}
           fi
           # copy landing page
           #cp -p ${week}/index.md ./website/content/${week}/
           # copy a directory and all its contents
           #cp -pr /some/path/lecs/${week}/assets /other/path/another/place/
           # copy files ending in .html and .css
           #cp  /some/path/lecs/${week}/*.{html,css} /other/path/another/place/
          done
          
      - name: Commit and push changes to website repo
        run: |
          cd ./website/
          git config --global user.email "andrewbray@berkeley.edu"
          git config --global user.name "andrewpbray"
          git commit -a -m "copied over from course-materials"
          git push https://${GITHUB_ACCESS_TOKEN}@github.com/stat20/website.git
